FROM cimg/base:2023.11-22.04

ENV VOLTA_VERSION=1.1.1 VOLTA_HOME="/home/circleci/.volta" PATH="$PATH:/home/circleci/.volta/bin"
RUN curl https://get.volta.sh | bash -s -- --skip-setup --version $VOLTA_VERSION
